### ISSUE TITLE
Add leaderboard for road and land

### ISSUE THREAD

**Issue by celery6** [BTE-Canada-USA/NASBS-BOT#1]
Add leaderboard for road and land points or area/distance. Maybe included in main leaderboard, or separately.

**Comment by the-irwin** [comment]
I can work on this

**Comment by the-irwin** [comment]
Added options to sort the leaderboard by number of buildings, road distance, and land area: #4

I could add the option to sort by road and land points, but that query would be annoying and might be a bit slow
