### ISSUE TITLE
update land points

### ISSUE THREAD

**Issue by celery6** [BTE-Canada-USA/NASBS-BOT#20]
Tier 1  Terrain - 8 pts - 100,000 sqm - Parking Lots/Fields/Farms/Orchards
Tier 2 Terrain - 10 pts - 100,000 sqm - Baller Terrain/Golf Courses
Tier 3 Terrain - 15 pts - 100,000 sqm - Garden Parks/Plazas

also, display land and road types as the actual word instead of the number in the reviewer embed.

**Comment by kgnar** [comment]
#22
